# Generated by Django 4.2.2 on 2023-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_active',
            field=models.BooleanField(default=False),
        ),
    ]
