# Generated by Django 4.2.2 on 2023-07-18 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('housename', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA'), ('TAMIL NADU', 'TAMIL NADU'), ('GOA', 'GOA'), ('GUJARAT', 'GUJARAT')], default='KERALA', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_store.userdetail')),
            ],
        ),
    ]
