# Generated by Django 4.2.2 on 2023-08-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
