# Generated by Django 4.2.1 on 2023-08-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0003_address_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
