# Generated by Django 4.2.1 on 2023-09-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image'),
        ('home_store', '0005_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
