# Generated by Django 4.2.1 on 2023-09-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0006_reviewrating_status_alter_reviewrating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
