# Generated by Django 4.2.1 on 2023-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_store', '0007_delete_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='u_otp',
            field=models.IntegerField(null=True),
        ),
    ]
