# Generated by Django 4.2.2 on 2023-08-07 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productgallery_product'),
        ('home_store', '0003_address_selected'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Paypal', 'Paypal'), ('Razorpay', 'Razorpay')], default='Cash on delivery', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Cancel Requested', 'Cancel Requested'), ('Return Requested', 'Return Requested'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_store.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.variation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_store.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('applied', models.BooleanField(default=False)),
                ('description', models.CharField(default='Sample', max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_store.userdetail')),
            ],
        ),
    ]
