# Generated by Django 4.2.2 on 2023-08-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_usercoupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='usercoupon',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
